/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    MetaMultisigWallet: {
      address: "0xb7f8bc63bbcad18155201308c8f3540b07f84f5e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "owners",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "requiredSigners",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "addSigner",
          inputs: [
            {
              name: "who",
              type: "address",
              internalType: "address",
            },
            {
              name: "newRequiredSigners",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "executeTransaction",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
            {
              name: "callData",
              type: "bytes",
              internalType: "bytes",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getHash",
          inputs: [
            {
              name: "funcName",
              type: "string",
              internalType: "string",
            },
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
            {
              name: "argument",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "isOwnerActive",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "removeSigner",
          inputs: [
            {
              name: "who",
              type: "address",
              internalType: "address",
            },
            {
              name: "newRequiredSigners",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "s_numRequiredSigners",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "s_owners",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "isActive",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "s_ownersLength",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferFunds",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "SignerAdded",
          inputs: [
            {
              name: "",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SignerRemoved",
          inputs: [
            {
              name: "",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "MetaMultisigWallet__AmountCannotBeZero",
          inputs: [],
        },
        {
          type: "error",
          name: "MetaMultisigWallet__NoZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "MetaMultisigWallet__NotEnoughBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "MetaMultisigWallet__TransferError",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
